# Generated by Django 2.0.4 on 2018-04-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180412_0931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
