# Generated by Django 2.0.4 on 2018-06-09 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YearBook',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='id', null=True, verbose_name='id')),
                ('title', models.CharField(db_column='标题', max_length=60, verbose_name='标题')),
                ('category', models.CharField(db_column='目录', max_length=60, verbose_name='目录')),
                ('page', models.CharField(db_column='年鉴页码', max_length=20, verbose_name='年鉴页码')),
                ('identify', models.CharField(db_column='编号', max_length=20, primary_key=True, serialize=False, verbose_name='编号')),
                ('caj', models.FilePathField(blank=True, db_column='CAJ', null=True, verbose_name='CAJ')),
                ('pdf', models.FilePathField(blank=True, db_column='PDF', null=True, verbose_name='PDF')),
                ('excel', models.FilePathField(blank=True, db_column='EXCEL', null=True, verbose_name='EXCEL')),
            ],
            options={
                'verbose_name': '农业统计年鉴详情',
                'db_table': '农业统计年鉴详情',
                'verbose_name_plural': '农业统计年鉴详情',
            },
        ),
        migrations.CreateModel(
            name='YearBookContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(db_column='顺序', verbose_name='顺序')),
                ('content', models.CharField(db_column='目录', max_length=40, verbose_name='目录')),
            ],
            options={
                'verbose_name': '农业统计年鉴目录',
                'db_table': '农业统计年鉴目录',
                'verbose_name_plural': '农业统计年鉴目录',
            },
        ),
        migrations.CreateModel(
            name='YearBookDes',
            fields=[
                ('year', models.CharField(db_column='年鉴年份', max_length=4, primary_key=True, serialize=False, verbose_name='年鉴年份')),
                ('index', models.CharField(db_column='编号', max_length=20, verbose_name='编号')),
                ('chinese', models.CharField(db_column='年鉴中文名', max_length=40, verbose_name='年鉴中文名')),
                ('english', models.CharField(db_column='年鉴英文名', max_length=60, verbose_name='年鉴英文名')),
                ('author', models.CharField(db_column='责任说明', max_length=20, verbose_name='责任说明')),
                ('unit', models.CharField(db_column='主编单位', max_length=60, verbose_name='主编单位')),
                ('pubtime', models.CharField(db_column='出版日期', max_length=20, verbose_name='出版日期')),
                ('page', models.CharField(db_column='页数', max_length=20, verbose_name='页数')),
                ('money', models.CharField(db_column='人民币定价', max_length=20, verbose_name='人民币定价')),
                ('desc', models.TextField(db_column='内容简介', verbose_name='内容简介')),
                ('image', models.ImageField(db_column='封面', upload_to='yearbooks/images/', verbose_name='封面')),
            ],
            options={
                'verbose_name': '农业统计年鉴概述',
                'db_table': '农业统计年鉴概述',
                'verbose_name_plural': '农业统计年鉴概述',
            },
        ),
        migrations.AddField(
            model_name='yearbookcontent',
            name='year',
            field=models.ForeignKey(db_column='年鉴年份', on_delete=django.db.models.deletion.DO_NOTHING, to='resource.YearBookDes', verbose_name='年鉴年份'),
        ),
        migrations.AddField(
            model_name='yearbook',
            name='year',
            field=models.ForeignKey(db_column='年鉴年份', on_delete=django.db.models.deletion.DO_NOTHING, to='resource.YearBookDes', verbose_name='年鉴年份'),
        ),
    ]
