# Generated by Django 2.0.4 on 2018-04-12 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearbook',
            name='year',
            field=models.ForeignKey(db_column='年鉴年份', on_delete=django.db.models.deletion.DO_NOTHING, to='resource.YearBookDes', verbose_name='年鉴年份'),
        ),
        migrations.AlterField(
            model_name='yearbookcontent',
            name='year',
            field=models.ForeignKey(db_column='年鉴年份', on_delete=django.db.models.deletion.DO_NOTHING, to='resource.YearBookDes', verbose_name='年鉴年份'),
        ),
    ]
